### ISSUE TITLE
Feature Request: Static id for artists

### ISSUE THREAD

**Issue by PZeide** [xSardine/AMQ-Artists-DB#2]
Hello,
I use your database in a project and I notice recently that artists ids are not static.
Whenever you change the artists mappings, every ids are scrambled around and this is really pain to work with.
This would be great if; when you add a new artist: a **unique** and **static** id is associated with it and if you remove it, the id become is unused.
Thanks a lot for your work on this database, this is really helpful !

**Comment by AnthonyGigerich** [comment]
Yeah, right now, it's very dumb scripts, and I regenerate the entire database on each update. I'm doing it that way because it makes it much easier for me to add new exceptions / informations, and this is something I do a lot, because I'm far from having added everything.

But I do understand how having an ID is useless for anyone else but me if I keep shifting them. ~~tho the API isn't even documented and I actually didn't even make a real one yet, so I didn't expect people to use it~~ 

I'll start writing the code to migrate on a stable database, and I hope it will be changed in the next few weeks. I need to make sure that when I do the swap, that it will not be a massive pain for me to make any change. Because there's a lot of stuff that could go wrong without me realizing it if for example I want to fuse two different artist because they are actually the same person and I didn't prepare such a process carefully. Right now I just go ["Minami", "Minami Kuribayashi"], done, everything regenerate and links itself to the right stuff.

Also this is still a work in progress, and you might be surprised with sudden database structure changes in the future, especially on artists, since I'm not really satisfied with them right now. I'll try to make sure to document those change whenever that happens tho, which I haven't until now.

**Comment by xSardine** [comment]
Yeah, right now, it's very dumb scripts, and I regenerate the entire database on each update. I'm doing it that way because it makes it much easier for me to add new exceptions / informations, and this is something I do a lot, because I'm far from having added everything.

But I do understand how having an ID is useless for anyone else but me if I keep shifting them. tho the API isn't even documented and I actually didn't even make a real one yet, so I didn't expect people to use it

I'll start writing the code to migrate on a stable database, and I hope it will be changed in the next few weeks. I need to make sure that when I do the swap, that it will not be a massive pain for me to make any change. Because there's a lot of stuff that could go wrong without me realizing it if for example I want to fuse two different artist because they are actually the same person and I didn't prepare such a process carefully. Right now I just go ["Minami", "Minami Kuribayashi"], done, everything regenerate and links itself to the right stuff.

Also this is still a work in progress, and you might be surprised with sudden database structure changes in the future, especially on artists, since I'm not really satisfied with them right now. I'll try to make sure to document those change whenever that happens tho, which I haven't until now.
