### ISSUE TITLE
Songs Missing: Docchi mo Maid

### ISSUE THREAD

**Issue by PZeide** [xSardine/AMQ-Artists-DB#6]
This entry is missing in the databse: Docchi mo Maid (https://www.animenewsnetwork.com/encyclopedia/anime.php?id=23271).

**Comment by xSardine** [comment]
Seems to me like it's in the database ?

**No relation to this because it's not missing, but since it is not completely clear from the main github readme (I'll improve it)**
For further notice, it is based of AMQ database, which means a song needs to fit AMQ requirements to also be here. I could technically add songs that are not in AMQ ~~which would help because some of their rules are dumb~~, but I'm refraining from it as of now for two reasons:
- I would like to share this database with AMQ in the future so that it would be possible to add an artist filter and an official S/A mode or stuff like that
- Would require a lot of manual work from me, and I still have some other aspect that also require manual input and that I'm prioritizing

Which means a song could be missing (and there are already a lot of such cases that I know) because it doesn't fit AMQ rules
